### ISSUE TITLE
Prohibit hierarchies of benchmark classes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/caliper#141]
```
Use getFields() rather than getDeclaredFields() Using only declared fields 
prevents benchmarks from sharing a common super class
```

Original issue reported on code.google.com by `mjduigou` on 20 Dec 2011 at 12:29

Attachments:
- [Parameter.java.patch](https://storage.googleapis.com/google-code-attachments/caliper/issue-141/comment-0/Parameter.java.patch)

**Comment by nglorioso** [comment]
This appears to be done: https://github.com/google/caliper/blob/7eb907479c54e5580b202ee3f590c0ba3426cfbd/caliper-core/src/main/java/com/google/caliper/core/BenchmarkClassModel.java#L55
