### ISSUE TITLE
Caliper seems to have painfully high overhead between trials

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/caliper#208]
```
I have some trials which should take only about (1 second + VM startup time), 
yet caliper is inching along at a rate of about 15 seconds per trial.

Can we please try to look into where all that time is going? It's quite 
excruciating and will definitely hamper users' willingness to run lots of 
trials of lots of parameters.
```

Original issue reported on code.google.com by `kevinb@google.com` on 29 Jan 2013 at 12:37

**Comment by nglorioso** [comment]
Sounds like the execution of trials is scheduled independently of the uploading now: https://github.com/google/caliper/blob/7eb907479c54e5580b202ee3f590c0ba3426cfbd/caliper-runner/src/main/java/com/google/caliper/runner/ExperimentingCaliperRun.java#L276
