### ISSUE TITLE
Guava confliction

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/caliper#296]
```
Hi,

I tried to use caliper for benchmarking guava related things.
But current caliper 1.0-beta1 release conflict with latest guava.

Could you release new one?
```

Original issue reported on code.google.com by `tokuhi...@gmail.com` on 20 Jun 2014 at 1:32

**Comment by netdpb** [comment]
Closing assuming this has been resolved by 1.0-beta-2. Please reopen if not.
