### ISSUE TITLE
Making ObjectExplorer more usable externally by making things public

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/caliper#307]
```
Is it possible to make ObjectExplorer usable publicly? For that, some things 
like subclasses of Chain would need to be made public. 
```

Original issue reported on code.google.com by `ser...@hortonworks.com` on 9 Mar 2015 at 11:59

**Comment by netdpb** [comment]
We aren't actively developing Caliper at this time, so we're unlikely to address feature requests.
