### ISSUE TITLE
Head build is failing

### ISSUE THREAD

**Issue by lazytosleep** [google/caliper#324]
Dagger dependency should be updated as 
 <dependency>
      <groupId>com.google.dagger</groupId>
      <artifactId>dagger</artifactId>
      <version>2.5-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.google.dagger</groupId>
      <artifactId>dagger-compiler</artifactId>
      <version>2.5-SNAPSHOT</version>
    </dependency>

**Comment by jshook** [comment]
Actually, now it should be just "2.5"

**Comment by cgruber** [comment]
I'll bump the POM's when I'm back in the office.

**Comment by ronshapiro** [comment]
I'm in today, I'll update them. It would be nice if we never had to think about this though and it just auto-updated

**Comment by cgruber** [comment]
Thanks Ron.  I'm back Monday if you don't get to it.

C.

**Comment by debmalya** [comment]
The following artifacts could not be resolved: com.google.dagger:dagger:jar:2.1-SNAPSHOT, com.google.dagger:dagger-compiler:jar:2.1-SNAPSHOT: Failure to find com.google.dagger:dagger:jar:2.1-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots

**Comment by ronshapiro** [comment]
Pretty sure we just need to sync caliper externally - the fix is already in
internally
