### ISSUE TITLE
Build is falling : Dagger and dagger-compiler jar is not being downloaded

### ISSUE THREAD

**Issue by mukteshkrmishra** [google/caliper#329]
Hi,

I am trying to build Caliper, however build is falling with below error:

The following artifacts could not be resolved: com.google.dagger:dagger:jar:2.1-SNAPSHOT, com.google.dagger:dagger-compiler:jar:2.1-SNAPSHOT: Could not find artifact com.google.dagger:dagger:jar:2.1-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)

Can you please check.

(PS: It is falling since in sonatype repo, the path for dagger jar has changed, instead of 2.1 it is now HEAD-SNAPSHOT. Thus it requires correction in pom.xml.)

**Comment by ronshapiro** [comment]
Check out #328. Should have this fixed soon.

If you need to fix it locally, just replace `2.1-SNAPSHOT` with `2.7`

**Comment by cgruber** [comment]
Not yet fixed, but should be shortly.

**Comment by ronshapiro** [comment]
Should be green (finally!) now
