### ISSUE TITLE
A simple example of how to use

### ISSUE THREAD

**Issue by binuidicula** [google/caliper#346]
team, can we have a simple how-to-use instructions on this library. 
I tried to do this without an IDE - just to build and see

1. git clone
2. cd caliper
3. mvn install
- It fails 'dependencies.dependency.systemPath' for com.google.android:android:jar must specify an absolute path but is ${env.ANDROID_HOME}/platforms/android-25/android.jar @ com.google.caliper:caliper-android:[unknown-version], /Users/idiculab/PerformanceOptimization/caliper/caliper-android/pom.xml, line 65, column 19

after that, I tried to build it inside caliper-examples
4. mvn install
ERROR] Failed to execute goal on project caliper-examples: Could not resolve dependencies for project com.google.caliper:caliper-examples:jar:1.0-SNAPSHOT: Failure to find com.google.caliper:caliper:jar:1.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

can you please help?

regards
Binu K Idicula

**Comment by nefk** [comment]
remove the Android module  and build the parent project

**Comment by cpovirk** [comment]
Done in https://github.com/google/caliper/commit/d495ae487a1ddd56d4383f2e58d93bfd3e91c879#diff-04c6e90faac2675aa89e2176d2eec7d8
