### ISSUE TITLE
microbenchmarks link in the home page of caliper wiki is not right

### ISSUE THREAD

**Issue by qudongfang** [google/caliper#406]
> Caliper takes measurements of your Java code. Our primary focus is microbenchmarks, but it can support arbitrary kinds of measurements including memory allocated, memory consumed, or arbitrary domain-specific measurements like compression ratio.

Please change `JavaMicrobenchmarks.md` to `JavaMicrobenchmarks`.

**Comment by kluever** [comment]
Done, thanks!
