### ISSUE TITLE
Say something about (a) JMH and (b) the Jetpack Benchmark library

### ISSUE THREAD

**Issue by cpovirk** [google/caliper#453]
My understanding is that our recommendation is that people should use JMH. We make an exception for Android (where JMH doesn't work), but I don't think Caliper works under Android externally, so we wouldn't need to cover that here.

(I recall discussing years ago how it would be nice if we could import JMH data into Caliper's pivot-table UI, but it's clear that's not happening anytime soon.)

**Comment by harshita19244** [comment]
@cpovirk could you please specify why JMH is recommended over Caliper? I am analyzing various tools available for writing benchmark tests, and it would be good to know why should I use JMH over Caliper.

**Comment by cpovirk** [comment]
The best explanation I have handy is https://groups.google.com/g/mechanical-sympathy/c/m4opvy4xq3U/m/7lY8x8SvHgwJ?pli=1

**Comment by harshita19244** [comment]
Is it still relevant, as most comments are from 6yrs ago

**Comment by cpovirk** [comment]
Sorry, typo: I don't think we have addressed any of those issues in the last *6* years.

**Comment by harshita19244** [comment]
Thank you so much, this was really helpful

**Comment by cpovirk** [comment]
A Caliper alternative on Android is [the Jetpack Benchmark library](https://developer.android.com/studio/profile/benchmark) ([via](https://jakewharton.com/which-is-better-on-android-divide-by-two-or-shift-by-one/)). We should say something about that, too.
